### ISSUE TITLE
code.commonmark.org and talk.commonmark.org no longer work

### ISSUE THREAD

**Issue by digitalmoksha** [commonmark/markdownhelp#73]
Neither https://code.commonmark.org/ or https://talk.commonmark.org/ are working for me - I get 500 errors

**Comment by jgm** [comment]
talk. works for me (just tried it).  Do you still experience the problem?
code. seems to be hanging.

**Comment by digitalmoksha** [comment]
`talk.` is now working for me as well 👍

**Comment by jgm** [comment]
I think I've now fixed code. as well.  I believe the problem is that we were redirecting to http instead of https.

**Comment by digitalmoksha** [comment]
@jgm Just tried `code.` this morning, it's still not working for me - same behavior.

**Comment by jgm** [comment]
It works for me -- hard to diagnose the issue if I can't reproduce it. Do you have any additional diagnostics, e.g. verbose output from curl?

**Comment by digitalmoksha** [comment]
Interesting.

If I enter `code.commonmark.org` or `http://code.commonmark.org` into Safari, it redirects to `https://github.com/commonmark/commonmark-spec`

If I click on the `code.commonmark.org` link on `https://commonmark.org`, or I enter `https://code.commonmark.org` into Safari, it hangs, and I eventually get 

<img width="1000" alt="Screenshot 2024-10-01 at 11 03 20 AM" src="https://github.com/user-attachments/assets/eb984627-419a-43ce-aa0c-a9316565f844">

Same thing happens with Chrome.

It seems like the `https` link is not being redirected, while `http` is

**Comment by jgm** [comment]
The domain registrar's documentation says:

> Please note that redirecting from https://domain1.tld to https://domain2.tld will also require both domains to have SSL certificates installed.

So maybe that is the issue?  If code.commonmark.org doesn't have an SSL cert installed?  @coding-horror

**Comment by ibudiallo** [comment]
FYI `talk.` works for me, however `https://code.commonmark.org/` is not working. It hangs for a while then times out
